Performance Improvement of Assessment Aggregator Flink Job
project-sunbird/sunbird-data-pipeline pull request #1202
Opened 2021-02-08 07:14 UTC by manjudr

…link Job.

2021-02-08 13:56 UTC, anandp504 requested changes

2021-02-08 13:56 UTC, anandp504 commented on data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/task/AssessmentAggregatorStreamTask.scala
> +    in.userId.hashCode % config.windowShards
Will it improve the performance if we use the userId, courseId as this composite key is the partitioning key in Cassandra?

2021-02-08 13:56 UTC, anandp504 commented on data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggWindowFun.scala
> +    values.asScala.map { res =>
Please use Scala lists everywhere. It looks like you want to return List[Map[String, String]] but the return type is List[Map[String, Any]]. What is the purpose of this JSON serialization?

2021-02-19 06:45 UTC, manjudr commented
These changes are no longer required hence closing this.

2021-02-19 06:45 UTC, closed without merging