Issue #SB-23540: Config changes for sourcing summary job
project-sunbird/sunbird-data-pipeline pull request #1328
Opened 2021-06-04 10:07 UTC by ishawakankar

2021-06-07 08:34 UTC, manjudr requested changes

2021-06-07 08:34 UTC, manjudr commented on ansible/roles/data-products-deploy/files/sourcing-ingestion-spec.json
> +                  "name": "userId",
Please follow the ingestion spec standard

2021-06-07 08:34 UTC, manjudr commented on ansible/roles/data-products-deploy/tasks/main.yml
Please add a cron job task.

2021-06-07 08:34 UTC, manjudr commented on ansible/roles/data-products-deploy/templates/model-dock-config.j2
> +	druidRollupHost="{{ druid_rollup_cluster_ingestion_task_url }}"
Hope this variable contains port as well.

2021-06-08 03:48 UTC, ishawakankar commented on ansible/roles/data-products-deploy/tasks/main.yml
Added

2021-06-08 14:50 UTC, SanthoshVasabhaktula approved these changes

2021-06-08 14:50 UTC, merged