SB-24793 - Assessment Agg Flink Job to Insert max_score value into the activity aggregator table
project-sunbird/sunbird-data-pipeline pull request #1371
Opened 2021-07-14 13:10 UTC by manjudr

Currently, We are storing only the best score value in the activity aggregate this changes to insert the max_score value of the question along with the best score value into the activity_agg Cassandra table `agg` column. 
Since to support as part of assessment data archival.

**Example** 
In agg column it will be having both max_score and best_score of the question
 `Map(score:do_212686723743318016173 -> 1, max_score:do_212686723743318016173 -> 2)`

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-12 06:05 UTC, maheshkumargangula approved these changes

2021-11-29 09:49 UTC, maheshkumargangula requested changes

2021-11-29 09:49 UTC, maheshkumargangula commented on data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/UserScoreAggregateFunction.scala
> +    } else Map[String, Double]()
Similar to `getAggregateDetails` function, can you please put this in a function and call.

2021-12-01 06:44 UTC, SanthoshVasabhaktula approved these changes

2021-12-01 06:44 UTC, merged