SB-26355 feat: Recompute best score aggregates
project-sunbird/sunbird-data-pipeline pull request #1424
Opened 2021-09-02 12:32 UTC by PradyumnaNagendra

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-02 16:39 UTC, maheshkumargangula requested changes

2021-09-02 16:39 UTC, maheshkumargangula commented on data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
> +          println("assessEvents for recompute::" + assessEvents)
```suggestion
```
Please use logger info.

2021-09-03 04:44 UTC, PradyumnaNagendra commented on data-pipeline-flink/assessment-aggregator/src/main/scala/org/sunbird/dp/assessment/functions/AssessmentAggregatorFunction.scala
> +          println("assessEvents for recompute::" + assessEvents)
Removed print statement

2021-09-08 06:37 UTC, maheshkumargangula approved these changes

2021-09-08 06:42 UTC, anandp504 approved these changes
Approved :+1:

2021-09-08 06:44 UTC, merged